#!/usr/bin/python

import wiringpi as wp
import time

wp.wiringPiSetupGpio()

#configure input and output pins
PWMPin = 18
Standby = 5
AIN1 = 23
AIN2 = 24


wp.pinMode(PWMPin, 2)
wp.pinMode(Standby, 1)
wp.pinMode(AIN1, 1)
wp.pinMode(AIN2, 1)
